%YAML:1.0
#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1        
num_of_cam: 2  

imu_topic: "/camera/imu"
image0_topic: "/camera/infra1/image_rect_raw"
image1_topic: "/camera/infra2/image_rect_raw"
output_path: "/home/phoenix/ros_ws/src/rsun_state_estimation/VINS-Fusion/trajectory"

cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"
image_width: 848
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

# body_T_cam0: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [0.99995186, 0.00370598, -0.00908498, 0.03042723,
#           -0.00374387, 0.99998435, -0.00415678, -0.00366892,
#           0.00906943, 0.00419059, 0.9999, -0.01693092,
#           0, 0, 0, 1.0]

# body_T_cam1: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [0.99996763, 0.00373132, -0.00712924, -0.06472219,
#           -0.00375991, 0.99998493, -0.0040008, -0.00388673,
#           0.00711421, 0.00402747, 0.99996658, -0.01662721,
#            0., 0., 0., 1.0]

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.99995186,  -0.00374387, 0.00906943, -0.03028595,
          0.00370598,  0.99998435 , 0.00419059, 0.00362705,
         -0.00908498,  -0.00415678, 0.99995009, 0.01719125,
          0, 0, 0, 1.0]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.99996763 ,-0.00375991, 0.00711421, 0.06482377,
          0.00373132 , 0.99998493, 0.00402747, 0.00419514,
          -0.00712924, -0.0040008, 0.99996658, 0.01614969,
           0., 0., 0., 1.0]


#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 25                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#### Original Noise values
#acc_n: 0.0357204785 
#gyr_n: 0.0076517323
#acc_w: 0.0033565968
#gyr_w: 0.0001903905

### Parameters (x5) due to noise change in IMU 
#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.0357204785          # accelerometer measurement noise standard deviation. 
gyr_n: 0.0076517323         # gyroscope measurement noise standard deviation.     
acc_w: 0.0033565968        # accelerometer bias random work noise standard deviation.  
gyr_w: 0.0001903905       # gyroscope bias random work noise standard deviation.     
g_norm: 9.80655000386     # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: -0.003353703919073599                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/phoenix/ros_ws/src/rsun_state_estimation/VINS-Fusion/trajectory/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
